import { Product } from '@/types'

export const products: Product[] = [
  {
    id: 1,
    slug: "ariana",
    name: "ARIANA",
    price: 1099,
    priceRange: null,
    description: "Handcrafted sandal with a beautiful stripe upper and comfortable leather insole.",
    features: ["Handcrafted", "Open toe", "Stripe upper", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: ["Flat", "Double", "Medium Wedge Sole", "High Wedge Sole"],
    toeOptions: [],
    colours: [],
    image: "/images/ariana.png",
    images: ["/images/ariana.png"],
    category: "Lynux",
    featured: false,
    rating: null,
    reviewCount: 0
  },
  {
    id: 2,
    slug: "carnero-slipper",
    name: "CARNERO SLIPPER",
    price: 1299,
    priceRange: null,
    description: "Handcrafted 100% sheep wool sandal with a comfortable leather insole.",
    features: ["Handcrafted", "100% Sheep wool upper", "Leather insole", "Slipper style"],
    sizes: [4,5,6,7,8,9],
    juteOptions: ["Flat", "Double"],
    toeOptions: [],
    colours: [],
    image: "/images/carnero-slipper.jpg",
    images: ["/images/carnero-slipper.jpg"],
    category: "Lynux",
    featured: false,
    rating: null,
    reviewCount: 0
  },
  {
    id: 3,
    slug: "florencia-cerrada",
    name: "FLORENCIA CERRADA",
    price: 1499,
    priceRange: null,
    description: "Handcrafted closed toe espadrille with premium leather finish.",
    features: ["Handcrafted", "Closed toe", "Premium leather", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: [],
    toeOptions: [],
    colours: [],
    image: "/images/florencia-cerrada.jpg",
    images: ["/images/florencia-cerrada.jpg"],
    category: "Lynux",
    featured: true,
    rating: null,
    reviewCount: 0
  },
  {
    id: 4,
    slug: "lucia-wedge",
    name: "LUCIA WEDGE",
    price: 1299,
    priceRange: null,
    description: "Handcrafted wedge espadrille with leopard print upper and leather insole.",
    features: ["Handcrafted", "Wedge sole", "Leopard print", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: [],
    toeOptions: [],
    colours: [],
    image: "/images/lucia-wedge.png",
    images: ["/images/lucia-wedge.png"],
    category: "Lynux",
    featured: true,
    rating: null,
    reviewCount: 0
  },
  {
    id: 5,
    slug: "renata",
    name: "RENATA",
    price: 999,
    priceRange: { min: 999, max: 1099 },
    description: "Handcrafted sandal with a clean, classic upper and leather insole.",
    features: ["Handcrafted", "Open toe", "Classic upper", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: ["Flat", "Double"],
    toeOptions: [],
    colours: [],
    image: "/images/renata.jpg",
    images: ["/images/renata.jpg"],
    category: "Lynux",
    featured: false,
    rating: null,
    reviewCount: 0
  },
  {
    id: 6,
    slug: "the-bella",
    name: "THE BELLA",
    price: 999,
    priceRange: null,
    description: "Tie up Gladiator sandal with adjustable string strap and leather insole.",
    features: ["Handcrafted", "Gladiator style", "Adjustable string strap", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: [],
    toeOptions: [],
    colours: [],
    image: "/images/the-bella.jpg",
    images: ["/images/the-bella.jpg"],
    category: "Lynux",
    featured: false,
    rating: null,
    reviewCount: 0
  },
  {
    id: 7,
    slug: "the-lynux",
    name: "THE LYNUX",
    price: 1099,
    priceRange: null,
    description: "The signature Lynux sandal. Handcrafted with linen upper, bow detail and leather insole. Our most loved style.",
    features: ["Handcrafted", "Open toe", "Linen upper", "Bow detail", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: ["Flat", "Double"],
    toeOptions: [],
    colours: [
      { name: "Baby Pink", hex: "#F4C2C2", image: null },
      { name: "Black", hex: "#1C1A17", image: "/images/the-lynux-3.jpg" },
      { name: "Grey", hex: "#9E9E9E", image: null },
      { name: "Ivory", hex: "#FFFFF0", image: null },
      { name: "Khaki", hex: "#C3B091", image: "/images/the-lynux-6.jpg" },
      { name: "Multi-Color", hex: null, image: "/images/the-lynux.png" },
      { name: "Navy", hex: "#003153", image: "/images/the-lynux-7.jpg" },
      { name: "Nude", hex: "#E8CFB0", image: "/images/the-lynux-4.jpg" },
      { name: "Olive", hex: "#6B7C45", image: "/images/the-lynux-5.jpg" },
      { name: "Orange", hex: "#E07B39", image: null },
      { name: "Rustic", hex: "#8B4513", image: null },
      { name: "White", hex: "#FDFCF9", image: null }
    ],
    image: "/images/the-lynux.png",
    images: [
      "/images/the-lynux.png",
      "/images/the-lynux-2.png",
      "/images/the-lynux-3.jpg",
      "/images/the-lynux-4.jpg",
      "/images/the-lynux-5.jpg",
      "/images/the-lynux-6.jpg",
      "/images/the-lynux-7.jpg",
      "/images/the-lynux-8.jpg"
    ],
    category: "Lynux",
    featured: true,
    rating: 5.0,
    reviewCount: 1,
    reviews: [
      {
        author: "Lynnet Chitungo",
        rating: 5,
        date: "2 December 2022",
        comment: "Like the colour, the comfort! Can wear this everyday!"
      }
    ]
  },
  {
    id: 8,
    slug: "the-mule",
    name: "THE MULE",
    price: 1299,
    priceRange: null,
    description: "Handcrafted open toe mule sandal with leather upper and comfortable leather insole.",
    features: [
      "Handcrafted",
      "Open toe",
      "Leather upper",
      "Leather insole",
      "Available in black and brown",
      "Available on jute flat, double, and light wedge sole"
    ],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: ["Flat", "Double"],
    toeOptions: ["Open Toe", "Closed Toe"],
    colours: [
      { name: "Black", hex: "#1C1A17", image: null },
      { name: "Brown", hex: "#7B4F2E", image: "/images/the-mule-2.jpg" }
    ],
    image: "/images/the-mule.webp",
    images: [
      "/images/the-mule.webp",
      "/images/the-mule-2.jpg",
      "/images/the-mule-3.jpg",
      "/images/the-mule-4.jpg",
      "/images/the-mule-5.webp"
    ],
    category: "Lynux",
    featured: true,
    rating: null,
    reviewCount: 0
  },
  {
    id: 9,
    slug: "the-tina",
    name: "THE TINA",
    price: 1099,
    priceRange: null,
    description: "Handcrafted sandal with cotton upper, adjustable ankle strap and leather insole.",
    features: ["Handcrafted", "Cotton upper", "Adjustable ankle strap", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: ["Flat", "Double", "Low Wedge Sole", "Medium Wedge Sole", "High Wedge Sole"],
    toeOptions: [],
    colours: [],
    image: "/images/the-tina.jpg",
    images: ["/images/the-tina.jpg"],
    category: "Lynux",
    featured: false,
    rating: null,
    reviewCount: 0
  },
  {
    id: 10,
    slug: "valeria",
    name: "VALERIA",
    price: 1099,
    priceRange: null,
    description: "Handcrafted sandal with adjustable string strap and leather insole.",
    features: ["Handcrafted", "Adjustable string strap", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: ["Flat", "Double"],
    toeOptions: [],
    colours: [],
    image: "/images/valeria.png",
    images: ["/images/valeria.png"],
    category: "Lynux",
    featured: false,
    rating: null,
    reviewCount: 0
  },
  {
    id: 11,
    slug: "ximera-leather",
    name: "XIMERA LEATHER",
    price: 1299,
    priceRange: null,
    description: "Handcrafted leather espadrille with premium finish and comfortable leather insole.",
    features: ["Handcrafted", "Premium leather upper", "Leather insole"],
    sizes: [3,4,5,6,7,8,9],
    juteOptions: ["Flat", "Double", "Medium Wedge Sole", "High Wedge Sole"],
    toeOptions: [],
    colours: [],
    image: "/images/ximera-leather.jpg",
    images: ["/images/ximera-leather.jpg"],
    category: "Lynux",
    featured: false,
    rating: null,
    reviewCount: 0
  }
]

export const getFeaturedProducts = () => products.filter(p => p.featured)
export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug)
export const getAllProducts = () => products
